### ISSUE TITLE
IBC: Exception occurred at TWS entry point: jclient.LoginFrame.main (TWS 10.35.1)

### ISSUE THREAD

**Issue by aladdinaire** [IbcAlpha/IBC#305]
When I run twsstart.sh, I am getting the following error message with TWS 10.35.1. There is no tws.jar file in the ~/Jts/1035/ folder. The files and folder that exist in ~/Jts/1035/ are as below:  data   jars  'Trader Workstation.desktop'   tws1   tws.vmoptions   uninstall

2025-04-21 00:07:12:409 IBC: Exception occurred at TWS entry point: jclient.LoginFrame.main
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
java.lang.NoClassDefFoundError: jclient/LoginFrame
	at ibcalpha.ibc.IbcTws.startTws(Unknown Source)
	at ibcalpha.ibc.IbcTws.startTwsOrGateway(Unknown Source)
	at ibcalpha.ibc.IbcTws.load(Unknown Source)
	at ibcalpha.ibc.IbcTws.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: jclient.LoginFrame
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
2025-04-21 00:07:12:410 IBC: Exiting with exit code=1107
IBC returned exit status 83
autorestart file not found

TWS finished

**Comment by rlktradewright** [comment]
Send the complete IBC logfile. Attach it to your reply, don't quote it inline.

**Comment by aladdinaire** [comment]
Thanks! It seems to work after I switch to TWS 10.30. I use Ubuntu. Can you get it to work with Ubuntu and TWS 10.35?

**Comment by rlktradewright** [comment]
Send me the IBC logfile! How many times do I have to ask?

I will try it on Ubuntu later today. The move to Java 17 on Ubuntu was made some time ago, so there should be no problem.

**Comment by rlktradewright** [comment]
The latest IBC version (3.21.2) works perfectly with TWS 10.35.1g.

**Comment by aladdinaire** [comment]
Interestingly, ibc is now working with TWS 10.35.1g for me. As a result, I can not reproduce the issued I had and send you the log because I deleted the old log files. The issue might be related to Java.
